export const products = [
  {
    id: "e1",
    title: "Sushi",
    description: "veggies",
    prais: 22.99,
  },
  {
    id: "e2",
    title: "Schnitzel",
    description: "specialty",
    prais: 16.0,
  },
  {
    id: "e3",
    title: "Barbecue Burger",
    description: "American, raw, meaty",
    prais: 12.99,
  },
  {
    id: "e4",
    title: "Green Bowl",
    description: "Healthy...and green...",
    prais: 19.99,
  },
  {
    id: "e4",
    title: "Green Bowl",
    description: "Healthy...and green...",
    prais: 19.99,
  },
  {
    id: "e4",
    title: "Green Bowl",
    description: "Healthy...and green...",
    prais: 19.99,
  },
  {
    id: "e4",
    title: "Green Bowl",
    description: "Healthy...and green...",
    prais: 19.99,
  },
  {
    id: "e4",
    title: "Green Bowl",
    description: "Healthy...and green...",
    prais: 19.99,
  },
  {
    id: "e4",
    title: "Green Bowl",
    description: "Healthy...and green...",
    prais: 19.99,
  },
  {
    id: "e1",
    title: "Sushi",
    description: "veggies",
    prais: 22.99,
  },
  {
    id: "e1",
    title: "Sushi",
    description: "veggies",
    prais: 22.99,
  },
  {
    id: "e1",
    title: "Sushi",
    description: "veggies",
    prais: 22.99,
  },
  {
    id: "e1",
    title: "Sushi",
    description: "veggies",
    prais: 22.99,
  },
  {
    id: "e1",
    title: "Sushi",
    description: "veggies",
    prais: 22.99,
  },
  {
    id: "e1",
    title: "Sushi",
    description: "veggies",
    prais: 22.99,
  },
];
